server:
  port: 8080

spring:
  application:
    name: kyma-api
    
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/kymadb
  username: postgres
  password: dev_router